#!/bin/bash
if [[ $1 == "build" ]]
then
    sudo docker build -t osoc_postgres_image_local_dev:latest .
elif [[ $1 == "run" ]]
then
    sudo docker run -d --name osoc_postgres_container_local_dev -p 5432:5432 -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -e POSTGRES_DB=osoc osoc_postgres_image_local_dev:latest
elif [[ $1 == "start" ]]
then
    sudo docker container start osoc_postgres_container_local_dev
elif [[ $1 == "stop" ]]
then
    sudo docker container stop osoc_postgres_container_local_dev
elif [[ $1 == "remove" ]] || [[ $1 == "rm" ]]
then
    sudo docker container rm osoc_postgres_container_local_dev
elif [[ $1 == "status" ]]
then
    sudo systemctl status docker
else 
    echo "Unknown command"
    echo "Possible commands are:"
    echo "  build"
    echo "  run"
    echo "  start"
    echo "  stop"
    echo "  remove"
    echo "  status"
fi

