name: Run backend all tests with maven

on:
  push:
    branches: [ master, development ]
    paths:
      - 'backend/**'
  pull_request:
    branches: 
      - '**'
    paths:
      - 'backend/**'

jobs:
  container-job:

    runs-on: ubuntu-latest
    container:
      image: mikxox/maven-test-action:latest
      options: --rm

    steps:
      - uses: actions/checkout@v2

      - name: Test with Maven
        # -B: run in non-interactive (batch) mode
        run: ./mvnw -B -DfailIfNoTests=false test --file pom.xml

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: true
          files: /__w/OSOC-1/OSOC-1/backend/target/site/jacoco/jacoco.xml
          flags: all_tests
          name: codecov-umbrella
          verbose: true
