name: backend-linting
on: [pull_request]

jobs:
  ktlint:
    name: Check Code Quality
    runs-on: self-hosted
    container:
      image: mikxox/maven-test-action:latest
    env:
      GITHUB_WORKSPACE: /home/selab2/actions-runner/workspace

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: 'temppath'
      - run: |
          cd /__w/OSOC-1/OSOC-1/temppath/backend
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.44.0/ktlint
          chmod a+x ktlint
      - name: run ktlint
        run: |
          ./ktlint --reporter=checkstyle,output=build/ktlint-report.xml
        continue-on-error: true
      - uses: yutailang0119/action-ktlint@v2
        with:
          report-path: build/*.xml # Support glob patterns by https://www.npmjs.com/package/@actions/glob
        continue-on-error: false # If annotations contain error of severity, action-ktlint exit 1.

#      - name: Ktlint check
#        run:
#          ./ktlint --verbose --debug --trace -F --color

#      - name: ktlint
#        uses: ScaCap/action-ktlint@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          reporter: github-pr-review
