name: backend-linting
on: [pull_request]

jobs:
  ktlint:
    name: Check Code Quality
    runs-on: self-hosted
    container:
      image: mikxox/maven-test-action:latest
    env:
      GITHUB_WORKSPACE: /home/selab2/actions-runner/workspace

    steps:
      - name: Clone repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: 'temppath'
      - run: |
          cd /__w/OSOC-1/OSOC-1/temppath/backend
          curl -sSLO https://github.com/pinterest/ktlint/releases/download/0.44.0/ktlint
          ls -la
          chmod a+x ktlint
          ls -la
          ktlint --verbose

#      - name: ktlint
#        uses: ScaCap/action-ktlint@master
#        with:
#          github_token: ${{ secrets.GITHUB_TOKEN }}
#          reporter: github-pr-review
