name: Lint Commit Messages
on: [push]

jobs:
  commitlint:
    runs-on: self-hosted
    container:
      image: mikxox/maven-test-action:latest

    env:
      GITHUB_WORKSPACE: /home/selab2/actions-runner/workspace

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          path: 'temppath'

      - name: Validate all commits from PR
        run: |
          cd /__w/OSOC-1/OSOC-1/temppath
          npx commitlint --verbose --from HEAD~1 --to HEAD
