name: Lint Commit Messages
on: [push]

jobs:
  commitlint:
    runs-on: self-hosted
    container:
      image: mikxox/maven-test-action:latest
    steps:
      - name: install git
        run: |
          apt update -y && apt install -y git
      - name: show env.GITHUB_WORKSPACE
        run: |
          echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
#       - uses: wagoid/commitlint-github-action@v4
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
      
      - name: Install commitlint
        run: npm install @commitlint/cli @commitlint/config-conventional

      - name: Validate all commits from PR
        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
