name: Lint Commit Messages
on: [push]

jobs:
  commitlint:
    runs-on: self-hosted
    container:
      image: mikxox/maven-test-action:latest

    env:
      GITHUB_WORKSPACE: /home/selab2/actions-runner/workspace

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: 'commitlint'

#      - run: |
#          cd /__w/OSOC-1/OSOC-1

      - name: Validate all commits from PR
        run: |
          cd /__w/OSOC-1/OSOC-1/commitlint
#          npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
          npx commitlint --verbose --from HEAD~1 --to HEAD --verbose