name: Lint Commit Messages
on: [push]

jobs:
  commitlint:
    runs-on: self-hosted
    container:
      image: mikxox/maven-test-action:latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - uses: wagoid/commitlint-github-action@v4
