name: Lint Commit Messages
on: [push]

jobs:
  commitlint:
    runs-on: ubuntu-latest
    container:
      image: mikxox/maven-test-action:latest
      options: --rm

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Validate all commits from PR
        shell: bash
        run: |
          STATUS="$(git log -1 --pretty=format:"%s" | npx commitlint)"
          echo -E ::notice title=commitmessage::$(git log -1 --pretty=format:"%s" | npx commitlint --verbose | sed 's/%/%25/g' | sed 's/\n/%0A/g' | sed 's/\r/%0D/g')

      - name: Validate all commits from PR
        shell: bash
        if: failure()
        run: |
          echo -E ::error title=commitmessage::$(git log -1 --pretty=format:"%s" | npx commitlint --verbose | sed 's/%/%25/g' | sed 's/\n/%0A/g' | sed 's/\r/%0D/g')
