name: Lint Commit Messages
on: [push]

jobs:
  commitlint:
    runs-on: self-hosted
    container:
      image: mikxox/maven-test-action:latest

    env:
      GITHUB_WORKSPACE: /home/selab2/actions-runner/workspace

    steps:
      - name: show env.GITHUB_WORKSPACE
          run: |
            echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          path: 'commitlint'
      - name: show env.GITHUB_WORKSPACE
          run: |
            echo "GITHUB_WORKSPACE = $GITHUB_WORKSPACE"

#      - name: Validate all commits from PR
#        run: npx commitlint --from ${{ github.event.pull_request.base.sha }} --to ${{ github.event.pull_request.head.sha }} --verbose
