name: Run backend unit tests with maven

on:
  push:
    branches:
      - '**'        # matches every branch
      - '!master'   # excludes master
      - '!development'   # excludes development
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - '**'        # matches every branch
      - '!master'   # excludes master
      - '!development'   # excludes development
    paths:
      - 'backend/**'

jobs:
  container-job:

    runs-on: self-hosted
    container: 
      image: mikxox/maven-test-action:latest
      options: --rm
    env:
      GITHUB_WORKSPACE: /home/selab2/actions-runner/workspace

    steps:
      - uses: actions/checkout@v2
        with:
          path: 'temppath'

      - name: Test with Maven
        # -B: run in non-interactive (batch) mode
        run: |
          cd /__w/OSOC-1/OSOC-1/temppath/backend
          ./mvnw -B -Dtest="unittests.**" -DfailIfNoTests=false test --file pom.xml

      - name: remove temppath
        if: always()
        run: |
          cd /__w/OSOC-1/OSOC-1/
          sudo rm -rf temppath
