name: Run backend unit tests with maven

on:
  push:
    branches:
      - '**'        # matches every branch
      - '!master'   # excludes master
      - '!development'   # excludes development
    paths:
      - 'backend/**'
  pull_request:
    branches:
      - '**'        # matches every branch
      - '!master'   # excludes master
      - '!development'   # excludes development
    paths:
      - 'backend/**'

jobs:
  container-job:

    runs-on: ubuntu-latest
    container: 
      image: mikxox/maven-test-action:latest
      options: --rm

    steps:
      - uses: actions/checkout@v2

      - name: Test with Maven
        # -B: run in non-interactive (batch) mode
        run: ./mvnw -B -Dtest="unittests.**" -DfailIfNoTests=false test --file pom.xml
        working-directory: ./backend
